overrides:
  - files:
      - "*.vue"
    options:
      semi: false # 不要分号
      bracketSameLine: true # 将结束标签放在同一行
  # - files:
  #     - "*.ts"
  #   options:
  #     bracketSpacing: true # 在对象文字中的括号之间打印空格
